### ISSUE TITLE
🛑 Landing Page is down

### ISSUE THREAD

**Issue by dqjackso** [CDMorpheus/cyber-dive-upptime#33]
In [`f7997d0`](https://github.com/CDMorpheus/cyber-dive-upptime/commit/f7997d0ea0ca9f3ace270d5993db36490c8d09c1
), Landing Page (https://parenting.cyberdive.co/revolutionary) was **down**:
- HTTP code: 404
- Response time: 947 ms

**Comment by CDMorpheus** [comment]
Resolved per WORK-11240
